Update release artifact location
projectriff-demo/demo pull request #28
Opened 2020-01-17 16:00 UTC by trisberg

2020-01-21 11:08 UTC, fbiville requested changes

2020-01-21 11:08 UTC, fbiville commented on README.md
> +1. Install the Streaming runtime by following instructions in the [Streaming Runtime Install section](https://projectriff.io/docs/latest/runtimes/streaming#install).
the instructions for Knative are missing, is that intentional?

2020-01-21 11:08 UTC, fbiville commented on README.md
> +1. Install the Core runtime by following instructions in the [Core Runtime Install section](https://projectriff.io/docs/latest/runtimes/core#install).
are we moving away from `riff-kapp-install.sh`?

2020-01-21 14:12 UTC, trisberg commented on README.md
> +1. Install the Streaming runtime by following instructions in the [Streaming Runtime Install section](https://projectriff.io/docs/latest/runtimes/streaming#install).
Knative is installed as part of the getting started doc - https://projectriff.io/docs/latest/getting-started/gke#install-riff-knative-runtime (we should remove the core once we switch demo to use knative deployers - https://github.com/projectriff-demo/demo/pull/27)

2020-01-21 14:15 UTC, trisberg commented on README.md
> +1. Install the Core runtime by following instructions in the [Core Runtime Install section](https://projectriff.io/docs/latest/runtimes/core#install).
No point maintaining separate install script once this demo is promoted as a general reference app for riff, I'd like to change the doc to not require a clone of the repo, just copy-n-paste.

2020-01-21 16:00 UTC, fbiville commented on README.md
> +1. Install the Streaming runtime by following instructions in the [Streaming Runtime Install section](https://projectriff.io/docs/latest/runtimes/streaming#install).
I don't see this link in the previous paragraph, yet this section starts with `Install riff with Core, Knative and Streaming runtimes plus their dependencies.`.

2020-01-21 16:19 UTC, trisberg commented on README.md
> +1. Install the Streaming runtime by following instructions in the [Streaming Runtime Install section](https://projectriff.io/docs/latest/runtimes/streaming#install).
The first item in the list of installs has link to install instructions that include  `riff build` and `riff knative runtime`

2020-01-21 16:30 UTC, fbiville commented on README.md
> +1. Install the Streaming runtime by following instructions in the [Streaming Runtime Install section](https://projectriff.io/docs/latest/runtimes/streaming#install).
gotcha

2020-01-22 12:00 UTC, fbiville approved these changes

2020-01-22 15:31 UTC, merged